name: Build

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: echo install dependencies
    - name: Build
      run: echo Execute build
    - name: Run tests
      run: echo test execution
    - name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true        
    - name: Connect to Logic App
      id: GetUrl
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $url = (Get-AzLogicAppTriggerCallbackUrl -ResourceGroupName actionsdemo -Name MyFirstLogiApp -TriggerName manual).Value
          if ($url)
          {
          
          echo "::set-output name=LogicAppUrl::$url"
          }          
        azPSVersion: '3.1.0'          
    - name: Initiate approval
      run: |
          $value = "${{ steps.GetUrl.outputs.LogicAppUrl }}" 
          if ($value)
          {
          echo $value
           - uses: CamiloGarciaLaRotta/watermelon-http-client@v1
          with:
          
             url: 'https://prod-56.westus.logic.azure.com:443/workflows/3be0d0c1205d4b5aa5ca67d992916643/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=AW8pY5d7dZaayU_E_ex2_ZMd05MgjQ-UpH6My0ebau0'
            method: post
            headers: '{"Content-Type": "application/json"}'
            data: '{ "approvers": "lohachan0108@gmail.com", "instructions":"Lorem Ipsum"}'

          }

          
